#!/bin/sh
#
# $relengid$
#
. ./releng.subr
TARGET="amd64"
TARGET_ARCH="amd64"
SRCBRANCH="base/stable/10@${_SVNREV}"
NODOC=yes
NOPORTS=
set -a
RELENGDIR="$(realpath $(dirname $(basename ${0})))/../release"
WORLD_FLAGS="-j10"
KERNEL_FLAGS="-j6"
EMBEDDEDBUILD=1
EMBEDDEDPORTS="lang/python textproc/gsed"
XDEV="arm"
XDEV_ARCH="armv6"
KERNEL="WANDBOARD-QUAD"
CROCHETSRC="https://github.com/glenbarber/crochet-freebsd"
CROCHETBRANCH="trunk"
__CONFIG_NAME="10-armv6-${KERNEL}-snap"
CHROOTDIR="${__WRKDIR_PREFIX}/${__CONFIG_NAME}"
set +a
