#!/bin/sh
#
# $FreeBSD$
#

BUILDBRANCH="10"

. "${__BUILDCONFDIR}/defaults-${BUILDBRANCH}.conf"

export RELENGDIR="$(realpath $(dirname $(basename ${0})))/../release"

export EMBEDDEDBUILD=1
export EMBEDDEDARCH="armv6"
export KERNEL="RPI-B"
export WORLD_FLAGS="-j10"
export KERNEL_FLAGS="-j6"

export NODOC=yes
export NOPORTS=

export EMBEDDEDPORTS="lang/python textproc/gsed"
export __CONFIG_NAME="${BUILDBRANCH}-${EMBEDDEDARCH}-${KERNEL}-${BUILDTYPE}"
export CHROOTDIR="${__WRKDIR_PREFIX}/${__CONFIG_NAME}"

export XDEV="arm"
export XDEV_ARCH="armv6"
export XDEV_FLAGS="WITH_GCC=1 WITH_GNUCXX=1 WITHOUT_CLANG_IS_CC=1"
export CROCHETSRC="https://github.com/kientzle/crochet-freebsd"
export CROCHETBRANCH="trunk"
export UBOOTSRC="https://github.com/gonzoua/u-boot-pi"
export UBOOTBRANCH="trunk"
export UBOOTDIR="/tmp/crochet/u-boot-rpi"

TARGET="amd64"
TARGET_ARCH="amd64"
