#!/bin/sh
#
# $FreeBSD: scripts/11-amd64-snap.conf 308 2013-10-17 16:51:19Z gjb $
# $relengid: user/gjb/scripts/release/11-armv6-RPI-B-snap.conf 781 2014-01-26 18:12:15Z gjb $
#
. ./releng.subr
TARGET="amd64"
TARGET_ARCH="amd64"
SRCBRANCH="base/stable/10@${_SVNREV}"
NODOC=yes
set -a
RELENGDIR="$(realpath $(dirname $(basename ${0})))/../release"
EMBEDDEDBUILD=1
EMBEDDEDPORTS="lang/python textproc/gsed"
XDEV="arm"
XDEV_ARCH="armv6"
KERNEL="RPI-B"
CROCHETSRC="https://github.com/kientzle/crochet-freebsd"
CROCHETBRANCH="trunk"
UBOOTSRC="https://github.com/gonzoua/u-boot-pi"
UBOOTBRANCH="trunk"
UBOOTDIR="/tmp/crochet/u-boot-rpi"
__CONFIG_NAME="10-armv6-${KERNEL}-snap"
CHROOTDIR="${__WRKDIR_PREFIX}/${__CONFIG_NAME}"
set +a
