#!/bin/sh
#
# $relengid$
#
. ./defaults-10.conf
TARGET="ia64"
TARGET_ARCH="ia64"
SRCBRANCH="base/stable/10@${_SVNREV}"
__CONFIG_NAME="10-${TARGET_ARCH}-${KERNEL}-snap"
CHROOTDIR="${__WRKDIR_PREFIX}/${__CONFIG_NAME}"
NOPORTS=1
