#!/bin/sh
#
# $relengid$
#
. ./defaults-10.conf
TARGET="powerpc"
TARGET_ARCH="powerpc"
SRCBRANCH="base/stable/10@${_SVNREV}"
__CONFIG_NAME="10-${TARGET_ARCH}-${KERNEL}-snap"
CHROOTDIR="${__WRKDIR_PREFIX}/${__CONFIG_NAME}"
WORLD_FLAGS="-j10"
