#!/bin/sh
#
# $FreeBSD: scripts/10-powerpc64-release.conf 342 2013-10-17 22:25:53Z gjb $
# $relengid$
#
. ./releng.subr
__CONFIG_NAME="10-powerpc64-release"
TARGET="powerpc"
TARGET_ARCH="powerpc64"
KERNEL="GENERIC64"
CHROOTDIR="${__WRKDIR_PREFIX}/${__CONFIG_NAME}"
SRCBRANCH="base/stable/10@${_SVNREV}"
