#!/bin/sh
#
# $relengid$
#

__SCRIPTDIR="$(dirname $(realpath ${0}))"
BUILDBRANCH="11"

. "${__SCRIPTDIR}/defaults-${BUILDBRANCH}.conf"

export RELENGDIR="$(realpath $(dirname $(basename ${0})))/../release"

export EMBEDDEDBUILD=1
export EMBEDDEDARCH="armv6"
export KERNEL="BEAGLEBONE"
export WORLD_FLAGS="-j10"
export KERNEL_FLAGS="-j6"

export NODOC=yes
export NOPORTS=

export EMBEDDEDPORTS="lang/python textproc/gsed"
export __CONFIG_NAME="${BUILDBRANCH}-${EMBEDDEDARCH}-${KERNEL}-${BUILDTYPE}"
export CHROOTDIR="${__WRKDIR_PREFIX}/${__CONFIG_NAME}"

load_chroot_env() {
	unset XDEV XDEV_ARCH
	export TARGET="amd64"
	export TARGET_ARCH="amd64"
}

load_target_env() {
	unset TARGET TARGET_ARCH
	export XDEV="arm"
	export XDEV_ARCH="armv6"
	export XDEV_FLAGS="WITH_GCC=1 WITH_GCC_BOOTSTRAP=1 WITHOUT_CLANG_IS_CC=1"
	export XDEV_FLAGS="${XDEV_FLAGS} MK_TESTS=no"
	export CROCHETSRC="https://github.com/kientzle/crochet-freebsd"
	export CROCHETBRANCH="trunk"
}

load_stage_env() {
	load_target_env
	TARGET=${XDEV}
	TARGET_ARCH=${XDEV_ARCH}
}

if [ ! -z ${FTP_STAGING} ]; then
	load_stage_env
fi
