#!/bin/sh
#
# $relengid$
#
. ./defaults-11.conf

SRCBRANCH="base/head@${_SVNREV}"
NODOC=yes
NOPORTS=
KERNEL="PANDABOARD"
WORLD_FLAGS="-j10"
KERNEL_FLAGS="-j6"
EMBEDDEDBUILD=1
EMBEDDEDPORTS="lang/python textproc/gsed"
RELENGDIR="$(realpath $(dirname $(basename ${0})))/../release"
__CONFIG_NAME="11-armv6-${KERNEL}-snap"
CHROOTDIR="${__WRKDIR_PREFIX}/${__CONFIG_NAME}"

load_chroot_env() {
	unset XDEV XDEV_ARCH
	export TARGET="amd64"
	export TARGET_ARCH="amd64"
}

load_target_env() {
	unset TARGET TARGET_ARCH
	export XDEV="arm"
	export XDEV_ARCH="armv6"
	export XDEV_FLAGS="WITH_GCC=1 WITH_GCC_BOOTSTRAP=1 WITHOUT_CLANG_IS_CC=1"
	export XDEV_FLAGS="${XDEV_FLAGS} MK_TESTS=no"
	export CROCHETSRC="https://github.com/kientzle/crochet-freebsd"
	export CROCHETBRANCH="trunk"
}

