#!/bin/sh
#
# $FreeBSD: scripts/11-amd64-snap.conf 308 2013-10-17 16:51:19Z gjb $
# $relengid$
#
. ./releng.subr
TARGET="amd64"
TARGET_ARCH="amd64"
SRCBRANCH="base/head@${_SVNREV}"
NODOC=yes
NOPORTS=
set -a
RELENGDIR="$(realpath $(dirname $(basename ${0})))/../release"
WORLD_FLAGS="-j10"
KERNEL_FLAGS="-j6"
EMBEDDEDBUILD=1
EMBEDDEDPORTS="lang/python textproc/gsed"
XDEV="arm"
XDEV_ARCH="armv6"
KERNEL="RPI-B"
CROCHETSRC="https://github.com/kientzle/crochet-freebsd"
CROCHETBRANCH="trunk"
UBOOTSRC="https://github.com/gonzoua/u-boot-pi"
UBOOTBRANCH="trunk"
UBOOTDIR="/tmp/crochet/u-boot-rpi"
__CONFIG_NAME="11-armv6-${KERNEL}-snap"
CHROOTDIR="${__WRKDIR_PREFIX}/${__CONFIG_NAME}"
set +a
