#!/bin/sh
#
# $FreeBSD: scripts/11-ia64-snap.conf 264 2013-10-11 20:56:03Z gjb $
# $relengid$
#
. ./releng.subr
__CONFIG_NAME="11-ia64-snap"
TARGET="ia64"
TARGET_ARCH="ia64"
CHROOTDIR="${__WRKDIR_PREFIX}/${__CONFIG_NAME}"
SRCBRANCH="base/head@${_SVNREV}"
