#!/bin/sh
#
# $relengid$
#
. ./releng.subr
TARGET="ia64"
TARGET_ARCH="ia64"
SRCBRANCH="base/head@${_SVNREV}"
__CONFIG_NAME="11-${TARGET_ARCH}-${KERNEL}-snap"
CHROOTDIR="${__WRKDIR_PREFIX}/${__CONFIG_NAME}"
NOPORTS=1
