#!/bin/sh
#
# $FreeBSD: scripts/11-powerpc-snap.conf 264 2013-10-11 20:56:03Z gjb $
# $relengid$
#
. ./releng.subr
__CONFIG_NAME="11-powerpc-snap"
TARGET="powerpc"
TARGET_ARCH="powerpc"
CHROOTDIR="${__WRKDIR_PREFIX}/${__CONFIG_NAME}"
SRCBRANCH="base/head@${_SVNREV}"
NODVD=1
