#!/bin/sh
#
# $relengid$
#
. ./releng.subr
TARGET="amd64"
TARGET_ARCH="amd64"
SRCBRANCH="base/stable/9@${_SVNREV}"
__CONFIG_NAME="9-${TARGET_ARCH}-${KERNEL}-snap"
CHROOTDIR="${__WRKDIR_PREFIX}/${__CONFIG_NAME}"
NOPORTS=1
