#!/bin/sh
#
# $relengid$
#

__SCRIPTDIR="$(dirname $(realpath ${0}))"
BUILDBRANCH="9"

. "${__SCRIPTDIR}/defaults-${BUILDBRANCH}.conf"

KERNEL="VT"
TARGET="amd64"
TARGET_ARCH="amd64"

__CONFIG_NAME="${BUILDBRANCH}-${TARGET_ARCH}-${KERNEL}-${BUILDTYPE}"
CHROOTDIR="${__WRKDIR_PREFIX}/${__CONFIG_NAME}"
