#!/bin/sh
#
# $FreeBSD: scripts/9-ia64-snap.conf 264 2013-10-11 20:56:03Z gjb $
# $relengid$
#
. ./releng.subr
TARGET="ia64"
TARGET_ARCH="ia64"
SRCBRANCH="base/stable/9@${_SVNREV}"
__CONFIG_NAME="9-${TARGET_ARCH}-${KERNEL}-snap"
CHROOTDIR="${__WRKDIR_PREFIX}/${__CONFIG_NAME}"
NOPORTS=1
