#!/bin/sh
#
# $relengid$
#

use_zfs=1
emailgoesto="gjb@FreeBSD.org"
scriptdir="$(dirname $(realpath ${0}))"
srcdir="${scriptdir}/../release"
logdir="${scriptdir}/../logs"
chroots="${scriptdir}/../chroots"

ftpdir="/relengftp"
ftpsubdir=
relengdir=

case $(hostname -s) in
	snap)
		zfs_root="zroot"
		zfs_mount="snap/releng"
		zfs_parent="${zfs_root}/${zfs_mount}"
		relengdir="/snap/releng"
		;;
	grind|releng1|releng2)
		zfs_root="zroot"
		zfs_mount="releng"
		zfs_parent="${zfs_root}/${zfs_mount}"
		relengdir="/releng"
		;;
	*)
		use_zfs=0
		;;
esac

export BUILDSVNREV="271779"
export BUILDDATE="20140918"
