#!/bin/sh
#
# $FreeBSD$
#

__WRKDIR_PREFIX=

unset CROCHETBRANCH
unset CROCHETSRC
unset XDEV
unset XDEV_ARCH
unset XDEV_FLAGS

case $(hostname -s) in
    grind|releng1|releng2)
	__WRKDIR_PREFIX="/releng"
	;;
    snap)
	__WRKDIR_PREFIX="/snap/releng"
	;;
    *)
	echo "__WRKDIR_PREFIX (top level work directory) not set for"
	echo "this build machine."
	exit 1
esac

SVNROOT="svn://svn.FreeBSD.org/"

KERNEL="GENERIC"
WORLD_FLAGS="-j $(( $(( $(sysctl -n hw.ncpu) + 1 )) / 2 ))"
KERNEL_FLAGS="-j $(( $(( $(sysctl -n hw.ncpu) + 1 )) / 2 ))"

CHROOTBUILD_SKIP=1
SRC_UPDATE_SKIP=1
PORTS_UPDATE_SKIP=1
DOC_UPDATE_SKIP=1
