#!/bin/sh
#
# $relengid$
#

export __BUILDCONFDIR="$(dirname $(realpath ${0}))"
. "${__BUILDCONFDIR}/allbuilds.conf"

releasesrc="stable/9/release"
heads=
stables="9"

revs="${heads} ${stables}"
archs="amd64 i386 ia64 powerpc powerpc64 sparc64 armv6"
types="snap"

kernels="GENERIC VT GENERIC64"
