#!/bin/sh
#
# $FreeBSD$
#

. "${__BUILDCONFDIR}/main.conf"

export BUILDSVNREV="271779"
export BUILDDATE="20140918"

releasesrc="stable/9/release"
heads=
stables="9"

revs="${heads} ${stables}"
archs="amd64 i386 ia64 powerpc powerpc64 sparc64 armv6"
types="snap"

kernels="GENERIC VT GENERIC64"
