#!/bin/sh
#
# $relengid$
#
use_zfs=1
emailgoesto="gjb@FreeBSD.org"
scriptdir="$(dirname $(realpath ${0}))"
srcdir="$(realpath ${scriptdir}/../release)"
logdir="$(realpath ${scriptdir}/../logs)"
chroots="$(realpath ${scriptdir}/../chroots)"

heads=
stables="9"

revs="${heads} ${stables}"
archs="amd64 i386 ia64 powerpc powerpc64 sparc64 armv6"
types="snap"

x86_kernels="GENERIC VT"
armv6_kernels="RPI-B BEAGLEBONE"

kernels="${x86_kernels} GENERIC64 ${armv6_kernels}"

ftpdir="/relengftp"
ftpsubdir=""

case $(hostname -s) in
    snap)
	zfs_root="zroot"
	zfs_mount="snap/releng"
	zfs_parent="${zfs_root}/${zfs_mount}"
	;;
    grind)
	zfs_root="zroot"
	zfs_mount="releng"
	zfs_parent="${zfs_root}/${zfs_mount}"
	;;
    *)
	use_zfs=0
	;;
esac

# These are separate from the variables used by the individual release
# configuration files for now.
BUILDSVNREV="263665"
BUILDDATE="20140323"

