#!/bin/sh
#
# $relengid$
#

. "${__SCRIPTDIR}/alldefaults.conf"

BUILDSVNREV="271779"
BUILDDATE="20140918"
BUILDTYPE="snap"

SRCBRANCH="base/stable/9@${BUILDSVNREV}"
PORTBRANCH="ports/head@HEAD"
DOCBRANCH="doc/head@HEAD"

WITH_DVD=
WITH_COMPRESSED_IMAGES=1
