#!/bin/sh
#
# $relengid$
#

__SCRIPTDIR="$(dirname $(realpath ${0}))"

__WRKDIR_PREFIX=

case `hostname -s` in
    snap)
	__WRKDIR_PREFIX="/snap/releng"
	;;
    bake | grind)
	__WRKDIR_PREFIX="/releng"
	;;
    *)
	echo "__WRKDIR_PREFIX (top level work directory) not set for"
	echo "this build machine."
	exit 1
	;;
esac

SVNROOT="svn://svn.FreeBSD.org/"
DOCBRANCH="doc/head@rHEAD"
PORTBRANCH="ports/head@rHEAD"
WORLD_FLAGS="-j10"
KERNEL_FLAGS="-j8"
KERNEL="GENERIC"
CHROOTBUILD_SKIP=1
WITH_COMPRESSED_IMAGES=1

# Skip doc/ and ports/ for now, this is only snapshot
NODOC=yes
#NOPORTS=yes

# Can't source files for these values, because we run with restricted
# environment.
_SVNREV="263906"
DATE="20140329"
