#!/bin/sh
#
# $relengid$
#

__SCRIPTDIR="$(dirname $(realpath ${0}))"

__WRKDIR_PREFIX=

case `hostname -s` in
    snap)
	__WRKDIR_PREFIX="/snap/releng"
	;;
    bake | grind)
	__WRKDIR_PREFIX="/releng"
	;;
    *)
	echo "__WRKDIR_PREFIX (top level work directory) not set for"
	echo "this build machine."
	exit 1
	;;
esac

SVNROOT="svn://svn.FreeBSD.org/"
DOCBRANCH="doc/head@rHEAD"
PORTBRANCH="ports/head@rHEAD"
WORLD_FLAGS="-j $(sysctl -n hw.ncpu)"
KERNEL_FLAGS="-j $(( $(( $(sysctl -n hw.ncpu) + 1 )) / 2 ))"
KERNEL="GENERIC"
CHROOTBUILD_SKIP=1
WITH_COMPRESSED_IMAGES=1
SRC_UPDATE_SKIP=1
DOC_UPDATE_SKIP=1
PORTS_UPDATE_SKIP=1

# Skip doc/ and ports/ for now, this is only snapshot
NODOC=1
NOPORTS=1

# Can't source files for these values, because we run with restricted
# environment.
_SVNREV="265621"
DATE="20140508"
