#!/bin/sh
#
# $FreeBSD$
#

# Lowercase variables are used by the build script.
# Uppercase variables are used by the individual build itself.

use_zfs=1
emailgoesto="gjb@FreeBSD.org"
scriptdir="$(dirname $(realpath ${0}))"
srcdir="${scriptdir}/../release"
logdir="${scriptdir}/../logs"
chroots="${scriptdir}/../chroots"

ftpdir="/relengftp"
ftpsubdir=
relengdir=

__WRKDIR_PREFIX=
unset CROCHETBRANCH CROCHETSRC XDEV XDEV_ARCH XDEV_FLAGS

case $(hostname -s) in
	snap)
		zfs_root="zroot"
		zfs_mount="snap/releng"
		zfs_parent="${zfs_root}/${zfs_mount}"
		relengdir="/snap/releng"
		__WRKDIR_PREFIX="${relengdir}"
		;;
	grind|releng1|releng2)
		zfs_root="zroot"
		zfs_mount="releng"
		zfs_parent="${zfs_root}/${zfs_mount}"
		relengdir="/releng"
		__WRKDIR_PREFIX="${relengdir}"
		;;
	*)
		use_zfs=0
		;;
esac

if [ -z "${__WRKDIR_PREFIX}" ]; then
	echo "__WRKDIR_PREFIX (top level work directory) not set for"
	echo "this build machine."
	exit 1
fi

if [ ! -e "${__BUILDCONFDIR}/svnrev_src" -o \
	! -e "${__BUILDCONFDIR}/builddate" ]; then
	echo "svnrev or builddate file does not exist."
	echo "Run 'setrev.sh -b <branch>' first."
	exit 1
fi

load_stage_env() { }

SVNROOT="svn://svn.FreeBSD.org/"

KERNEL="GENERIC"
WORLD_FLAGS="-j $(( $(( $(sysctl -n hw.ncpu) + 1 )) / 2 ))"
KERNEL_FLAGS="-j $(( $(( $(sysctl -n hw.ncpu) + 1 )) / 2 ))"

CHROOTBUILD_SKIP=1
SRC_UPDATE_SKIP=1
PORTS_UPDATE_SKIP=1
DOC_UPDATE_SKIP=1
# Hack to unset the exported BOARDNAME from sourced arm/armv6 configuration
# files.
unset BOARDNAME
