#!/bin/sh
#
# $relengid$
#
use_zfs=1
emailgoesto="gjb@FreeBSD.org"
scriptdir="$(dirname $(realpath ${0}))"
srcdir="${scriptdir}/../release"
logdir="${scriptdir}/../logs"
chroots="${scriptdir}/../chroots"

heads="11"
stables="10 9"

revs="${heads} ${stables}"
archs="amd64 i386 ia64 powerpc powerpc64 sparc64"
types="snap"

ftpdir="/relengftp"
ftpsubdir=""

case $(hostname -s) in
    snap)
	zfs_parent="zroot/snap/releng"
	;;
    grind)
	zfs_parent="zroot/releng"
	;;
    *)
	use_zfs=0
	;;
esac

# These are separate from the variables used by the individual release
# configuration files for now.
BUILDSVNREV="260369"
BUILDDATE="20140106"

