#
# $relengid$
#

## Set the directory within which the release will be built.
#CHROOTDIR="/scratch"

## Set the default svn checkout server, and branches for the src/, doc/, and
## ports/ trees.
#SVNROOT="svn://svn.freebsd.org"
#SRCBRANCH="base/head"
#DOCBRANCH="doc/head"
#PORTBRANCH="ports/head"

## Set the default src/, doc/, and ports/ revisions.
#SRCREVISION="-r HEAD"
#DOCREVISION="-r HEAD"
#PORTREVISION="-r HEAD"

## Sets the default make.conf and src.conf to use.  Set to /dev/null
## by default to avoid polluting the chroot(8) environment with
## non-default settings.
#MAKE_CONF="/dev/null"
#SRC_CONF="/dev/null"

## Sets HOST_ARCH to the architecture on which the release build is run.
#HOST_ARCH="`uname -p`"
#ARCH="${HOST_ARCH}"
#MACHINE_ARCH="${HOST_ARCH}"

## Sets the TARGET, and TARGET_ARCH for the release build for
## cross-architecture builds.  Defaults to the architecture
## of the machine on which the release build is run.
#TARGET="${HOST_ARCH}"
#TARGET_ARCH="${HOST_ARCH}"

## Set the number of make(1) jobs.
#NCPU="`sysctl -n hw.ncpu`"
#MAKE_FLAGS="-j${NCPU}"
