#!/bin/sh
#
# $FreeBSD: scripts/snapshot.conf 296 2013-10-14 23:57:15Z root $
# $relengid$
#

emailgoesto="gjb@FreeBSD.org"

svn="/usr/local/bin/svn"
svnhost="svn://svn.freebsd.org"
srcbase="${svnhost}/base"

chrootdir="/snap/releng"
chrootbuild="${chrootdir}/chroot"
chrootbuild9="${chrootdir}/chroot9"
relengdir="${chrootdir}/scripts"
logdir="${chrootdir}/logs"
distdir="${chrootdir}/distfiles"
ftpdir="${chrootdir}/../ftp/snapshots"

builddate="$(cat ${relengdir}/builddate)"
svnrev="r$(cat ${relengdir}/svnrev.txt)"

heads="11"
stables=""
revs="${heads}"
archs="amd64 i386 powerpc powerpc64 sparc64 ia64"
types="snap"

wflags="-s -j12 __MAKE_CONF=/dev/null SRCCONF=/dev/null"
iflags="-s __MAKE_CONF=/dev/null SRCCONF=/dev/null"

