#!/bin/sh
#
# $FreeBSD$
#

BUILDBRANCH="13"

. "${__BUILDCONFDIR}/defaults-${BUILDBRANCH}.conf"

TARGET="amd64"
TARGET_ARCH="amd64"

__CONFIG_NAME="${BUILDBRANCH}-${TARGET_ARCH}-${KERNEL}-${BUILDTYPE}"
CHROOTDIR="${__WRKDIR_PREFIX}/${__CONFIG_NAME}"

. ${srcdir}/${TARGET}/${TARGET_ARCH}.conf

WITH_VMIMAGES=1
WITH_COMPRESSED_VMIMAGES=1
WITH_CLOUDWARE=1
AWSREGION=us-west-2
AWSBUCKET=freebsd-release-staging
AWSKEYFILE=/root/Amazon-EC2
EC2PUBLIC=1
EC2PUBLICSNAP=1
EC2SNSTOPIC=arn:aws:sns:us-east-1:118940168514:FreeBSDAMI
GCE_BUCKET=freebsd-org-cloud-dev
GCE_CONFIG_PKG=/root/gcloud.tgz
GCE_CONFIG_LOC=/root/.config
GCE_CONFIG_DIR="${GCE_CONFIG_LOG}/gcloud"
GCE_LICENSE='--licenses="projects/freebsd-org-cloud-dev/global/licenses/freebsd"'
GCE_LOGIN_SKIP=1
VAGRANT_UPLOAD_CONF=/root/Hashicorp-Keys
