#!/bin/sh
#
# $FreeBSD$
#

. "${__BUILDCONFDIR}/main.conf"

releasesrc="main"
heads=14
stables=

revs="${heads} ${stables}"
archs="amd64 i386 powerpc powerpc64 powerpc64le powerpcspe armv6 armv7 aarch64 riscv64"
types="snap"

x86_kernels="GENERIC"
arm_kernels="ALLWINNER_UP"
arm_kernels="${arm_kernels} RPI RPI-B PINE64 PINE64-LTS GENERICSD"
arm_kernels="${arm_kernels} PINEBOOK ROCK64 ROCKPRO64"
kernels="${x86_kernels} GENERIC64 ${arm_kernels} MPC85XXSPE GENERIC64LE"

portsbranch="main"
srcbranch="${releasesrc}"
docbranch="main"
