#!/bin/sh
#
# $FreeBSD$
#

. "${__BUILDCONFDIR}/main.conf"

BUILDTYPE="snap"

# XXX: Unused now?
SRCBRANCH="main"
PORTSBRANCH="main"
DOCBRANCH="main"

WITH_DVD=
WITH_COMPRESSED_IMAGES=1
XZ_THREADS=10

KERNEL_FLAGS=""
NODOC=1
