#!/bin/sh
#
# $FreeBSD$
#

. "${__BUILDCONFDIR}/main.conf"

BUILDTYPE="snap"

# Used by release.sh, but ignored/unused for thermite.sh.
SRCBRANCH="stable/14"
PORTSBRANCH="main"
DOCBRANCH="main"

WITH_DVD=
WITH_COMPRESSED_IMAGES=1
XZ_THREADS=10

KERNEL_FLAGS=""
NODOC=1
