.\"
.Dd July 4, 2015
.Dt setrev.sh 8
.Os
.Sh NAME
.Nm setrev.sh
.Nd Branch revision and build date extractor
.Sh SYNOPSIS
.Nm programname
.Op Fl options
.Ar
.Sh DESCRIPTION
The
.Nm
[...]
.Sh ENVIRONMENT
The
.Nm
utility intentionally ignores environment variables set by the user.
.Sh EXAMPLES
.Sh NOTES
.Sh SEE ALSO
.Xr build 7 ,
.Xr release 7 ,
.Xr releasebuild 7
.Sh AUTHORS
The
.Nm
utility and this manual page were written by
.An Glen Barber Aq gjb@FreeBSD.org
for the
.Fx
Release Engineering Team, under sponsorship from the
.Fx
Foundation.
